framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'contact@todo.com'
        headers:
            from: 'Todo <contact@todo.com>'
            to: 'admin@todo.com'